# Site settings
title: Sonar Plugins
email: sonarplugins@gmail.com
url: https://example.github.io
description: "Sonar Plugins site includes a list of all the existing plugins for SonarQube. Use this site to add new functionalities to your SonarQube instance."
skills: "SonarQube Plugins"
meta_author: Plugins Sonar

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sonar Plugins
  location: 
  social:
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line:

# Credits content
credits: 'Sonar Plugins is just a site to list all SonarQube extensions around the world. We just provide the information and we don't have any responsability about the plugins development and use. '

# Build settings
markdown: kramdown
permalink: pretty
